# Generated by Django 5.1 on 2024-08-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Глубина'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ширина'),
        ),
    ]
