# Generated by Django 5.1 on 2024-08-31 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0002_remove_product_size_product_height_product_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Вид мебели')),
            ],
            options={
                'verbose_name': 'Вид мебели',
                'verbose_name_plural': 'Вид мебели',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loft.kindcategory', verbose_name='Вид'),
        ),
    ]
