# Generated by Django 5.1 on 2024-10-02 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0008_customer_order_orderproduct_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loft.region', verbose_name='Регион'),
        ),
    ]
