# Generated by Django 5.1 on 2024-10-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0010_saveorder_saveorderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveorderproduct',
            name='photo',
            field=models.ImageField(upload_to='images/', verbose_name='Фото товара'),
        ),
    ]
