# Generated by Django 5.1 on 2024-10-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0011_alter_saveorderproduct_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта пользователя')),
                ('offer', models.TextField(verbose_name='Предложение пользователя')),
            ],
            options={
                'verbose_name': 'Продложение',
                'verbose_name_plural': 'Предложения покупатеелй',
            },
        ),
    ]
